version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  ai:
    container_name: aimon-ai
    build:
      context: ./apps/ai
      dockerfile: Dockerfile
    image: aimon/ai:latest
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"

  backend:
    container_name: aimon-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env.dev
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:
